FROM node:18 as builder_client
COPY . .
RUN npm ci
RUN npm run build

FROM nginx:alpine3.17-slim
COPY ./src/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder_client ./build /usr/share/nginx/html
