version: '3.1'

services:
  mongo:
    container_name: senior-movie-selector-mongo-dev
    image: mongo:4.4.18
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: films
    volumes:
      - type: bind
        source: ./mongo/db
        target: /data/db
    ports:
      - 27017:27017

  client:
    container_name: senior-movie-selector-client-dev
    restart: unless-stopped
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    ports:
      - 80:80

  db-client:
    container_name: senior-movie-selector-db-client-dev
    restart: unless-stopped
    build:
      context: ./db-client/
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000

  db-server:
    container_name: senior-movie-selector-db-server-dev
    restart: unless-stopped
    build:
      context: ./db-server/
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  fileserver:
    container_name: senior-movie-selector-fileserver-dev
    restart: unless-stopped
    build:
      context: ./fileserver/
      dockerfile: Dockerfile
    volumes:
      - ./fileserver/:/movie-app/:ro
      - ./fileserver/films/:/movie-app/films:ro
      - ./fileserver/poster/:/movie-app/poster:ro
    ports:
      - 1337:1337
