version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: films
    volumes:
      - type: bind
        source: ./mongo/db
        target: /data/db
    ports:
      - 27017:27017
    networks:
      - default

  client:
    restart: unless-stopped
    build:
        context: ./client/
        dockerfile: Dockerfile
    ports:
        - 3001:3001
    networks:
      - default
    depends_on:
      - db-server

  db-client:
    restart: unless-stopped
    build:
      context: ./db_client/
      dockerfile: Dockerfile
    ports:
        - 8000:8000
    networks:
      - default
    depends_on:
      - db-server
  
  db-server:
    restart: unless-stopped
    build:
        context: ./db_server/
        dockerfile: Dockerfile
    ports:
        - 3000:3000
    networks:
      - default
    depends_on:
      - mongo
  
  fileserver:
    restart: unless-stopped
    build:
      context: ./videoplayer/
      dockerfile: Dockerfile
    volumes:
      - ./videoplayer/:/movie-app/:ro
    ports:
      - 1337:1337
    networks:
      - default