version: '3.1'

services:
  mongo:
    container_name: senior-movie-selector-mongo
    image: mongo:4.4.18
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: films
    volumes:
      - type: bind
        source: ./mongo/db
        target: /data/db
    ports:
      - 27017:27017

  client:
    container_name: senior-movie-selector-client
    restart: unless-stopped
    build:
      context: ./client/
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - db-server

  db-client:
    container_name: senior-movie-selector-db-client
    restart: unless-stopped
    build:
      context: ./db-client/
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    depends_on:
      - db-server

  db-server:
    container_name: senior-movie-selector-db-server
    restart: unless-stopped
    build:
      context: ./db-server/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo

  fileserver:
    container_name: senior-movie-selector-fileserver
    restart: unless-stopped
    build:
      context: ./fileserver/
      dockerfile: Dockerfile
    volumes:
      - ./films/:/movie-app/films:ro
      - ./poster/:/movie-app/poster:ro
    ports:
      - 1337:1337
