name: Docker

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  PASSWORD: ${{ secrets.GH_PAT }}
  BASE_TAG: ghcr.io/johannesfleischer/senior-movie-selector
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Registry
        run:  docker login --username JohannesFleischer --password $PASSWORD $REGISTRY
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Images
        run: |
          docker buildx create --use
          docker buildx build -f ./client/Dockerfile.prod ./client --platform $PLATFORMS --tag $BASE_TAG-client:latest --push
          docker buildx build -f ./db-client/Dockerfile.prod ./db-client --platform $PLATFORMS --tag $BASE_TAG-db-client:latest --push
          docker buildx build ./db-server --platform $PLATFORMS --tag $BASE_TAG-db-server:latest --push
          docker buildx build ./fileserver --platform $PLATFORMS --tag $BASE_TAG-fileserver:latest --push
